ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS avatar_crop_x REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS avatar_crop_y REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS avatar_zoom REAL NOT NULL DEFAULT 1;
